//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dynmicMenu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class MainMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainMenu()
        {
            this.SubMenus = new HashSet<SubMenu>();
        }
    
        public int id { get; set; }
        [DisplayName("Menü ismi")]
        public string menuname { get; set; }
        [DisplayName("Menü Url")]
        public string menuurl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubMenu> SubMenus { get; set; }
    }
}
